default: &default
  adapter: postgresql
  username: root
  password: root
  host: localhost
  port: 5432
  encoding: unicode
  pool: 5
  timeout: 5000
development:
  <<: *default
  database: invoice
  username: root
  password: root


production:
  <<: *default
  database: invoice
  username: root
  password: root